# Generated by Django 4.1.3 on 2023-02-05 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.CharField(default=datetime.datetime(2023, 2, 5, 14, 28, 33, 455037, tzinfo=datetime.timezone.utc), max_length=3),
            preserve_default=False,
        ),
    ]
