# Generated by Django 4.1.3 on 2023-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalapp', '0002_client_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='request',
            field=models.CharField(choices=[('', 'Please Select Case Category'), ('Tax Matters', 'Tax Matters'), ('Employment', 'Employment'), ('Business Transaction', 'Business Transaction'), ('Debt Recovery', 'Debt Recovery'), ('Civil Matters', 'Civil Matters'), ('Child Custody', 'Child Custody'), ('Property', 'Property'), ('Disput', 'Disput'), ('Immigration', 'Immigration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
