# Generated by Django 4.1.3 on 2023-02-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalapp', '0003_client_request_alter_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=200)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('', 'Select Lawyer Category'), ('Tax Lawyer', 'Tax Lawyer'), ('Immigration Lawyer', 'Immigration Lawyer'), ('Transactional Lawyer', 'Transactional Lawyer'), ('Public Interest Lawyer', 'Public Interest Lawyer'), ('Dispute Resolution Lawyer', 'Dispute Resolution Lawyer'), ('Worker Compensation Lawyer', 'Worker Compensation Lawyer'), ('Contract Lawyer', 'Contract Lawyer'), ('Civil Litigation Lawyer', 'Civil Litigation Lawyer'), ('Social Security Disability Lawyer', 'Social Security Disability Lawyer'), ('General Practice Lawyer', 'General Practice Lawyer')], max_length=100, null=True)),
                ('Experience', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
