# Generated by Django 4.1.3 on 2023-02-01 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyercat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lawyer_Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='pics')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lawyercat')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='pics')),
                ('Case_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.case')),
                ('Lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lawyer')),
            ],
        ),
    ]
