# Generated by Django 4.1.3 on 2023-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.EmailField(max_length=12)),
                ('gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=25)),
                ('case_type', models.CharField(choices=[('', 'Please Select Case Category'), ('Tax Matters', 'Tax Matters'), ('Employment', 'Employment'), ('Business Transaction', 'Business Transaction'), ('Debt Recovery', 'Debt Recovery'), ('Civil Matters', 'Civil Matters'), ('Child Custody', 'Child Custody'), ('Divorce', 'Divorce'), ('Property', 'Property'), ('Dispute', 'Dispute'), ('Immigration', 'Immigration')], max_length=100, null=True)),
                ('description', models.TextField()),
                ('profile', models.ImageField(upload_to='pics')),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firm', models.CharField(max_length=200)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=100)),
                ('Lawyer_type', models.CharField(choices=[('', 'Select Lawyer Category'), ('Tax Lawyer', 'Tax Lawyer'), ('Immigration Lawyer', 'Immigration Lawyer'), ('Transactional Lawyer', 'Transactional Lawyer'), ('Public Interest Lawyer', 'Public Interest Lawyer'), ('Dispute Resolution Lawyer', 'Dispute Resolution Lawyer'), ('Worker Compensation Lawyer', 'Worker Compensation Lawyer'), ('Contract Lawyer', 'Contract Lawyer'), ('Civil Litigation Lawyer', 'Civil Litigation Lawyer'), ('Social Security Disability Lawyer', 'Social Security Disability Lawyer'), ('General Practice Lawyer', 'General Practice Lawyer')], max_length=100, null=True)),
                ('Experience', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=6)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=12)),
                ('Phone', models.CharField(max_length=15)),
                ('Profile', models.ImageField(upload_to='pics')),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
