# Generated by Django 4.1.3 on 2023-02-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='Gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=6)),
                ('case_type', models.CharField(choices=[('', 'Please Select Case Category'), ('Tax Matters', 'Tax Matters'), ('Employment', 'Employment'), ('Business Transaction', 'Business Transaction'), ('Debt Recovery', 'Debt Recovery'), ('Civil Matters', 'Civil Matters'), ('Child Custody', 'Child Custody'), ('Divorce', 'Divorce'), ('Property', 'Property'), ('Dispute', 'Dispute'), ('Immigration', 'Immigration')], max_length=50)),
                ('situation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.lawyer')),
            ],
            options={
                'verbose_name': 'cases',
                'verbose_name_plural': 'cases',
            },
        ),
    ]
