# Generated by Django 4.1.3 on 2023-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_cases_case_id_alter_cases_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.ImageField(blank=True, default='profile_picture', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='Profile',
            field=models.ImageField(blank=True, default='profile_picture', upload_to='pics'),
        ),
    ]
