# Generated by Django 4.1.3 on 2023-02-05 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='category',
            field=models.CharField(default=datetime.datetime(2023, 2, 5, 1, 54, 9, 976227, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
    ]
